BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('AUTHORS', 'BOOKS', 'BOOK_COPIES', 'AUDIT_LOG', 'REPORTS_LOGS')) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/


-- Таблица Authors (Авторы)
CREATE TABLE Authors (
    author_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    full_name   VARCHAR2(100) NOT NULL,
    birth_date  DATE,
    created_at  DATE DEFAULT SYSDATE,
    CONSTRAINT pk_authors PRIMARY KEY (author_id)
);

-- Таблица Books (Книги)
CREATE TABLE Books (
    book_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    author_id   NUMBER NOT NULL,
    title       VARCHAR2(200) NOT NULL,
    genre       VARCHAR2(100),
    published_date DATE,
    created_at  DATE DEFAULT SYSDATE,
    CONSTRAINT pk_books PRIMARY KEY (book_id),
    CONSTRAINT fk_books_author FOREIGN KEY (author_id)
       REFERENCES Authors (author_id)
);

-- Таблица Book_Copies (Экземпляры книг)
CREATE TABLE Book_Copies (
    copy_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    book_id     NUMBER NOT NULL,
    copy_number VARCHAR2(50),
    condition   VARCHAR2(100),
    created_at  DATE DEFAULT SYSDATE,
    CONSTRAINT pk_book_copies PRIMARY KEY (copy_id),
    CONSTRAINT fk_book_copies_book FOREIGN KEY (book_id)
       REFERENCES Books (book_id)
);

-- Таблица Audit_Log (Журнал изменений)
CREATE TABLE Audit_Log (
    audit_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    table_name     VARCHAR2(50),
    pk_value       VARCHAR2(100),
    changed_data   VARCHAR2(4000),
    operation_type CHAR(1),
    change_time    TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_audit_log PRIMARY KEY (audit_id)
);

-- Таблица Reports_Logs (Журнал отчетов)
CREATE TABLE Reports_Logs (
    report_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    report_date    TIMESTAMP DEFAULT SYSTIMESTAMP,
    report_content VARCHAR2(4000),
    CONSTRAINT pk_reports_logs PRIMARY KEY (report_id)
);


SELECT * FROM Authors;
SELECT * FROM Books;
SELECT * FROM Book_Copies;
SELECT * FROM Audit_Log;
SELECT * FROM Reports_Logs;


