-- Создание пользователя C##DEV
CREATE USER C##DEV IDENTIFIED BY qwerty;
GRANT ALL PRIVILEGES TO C##DEV;

-- Создание таблиц в схеме C##DEV
CREATE TABLE C##DEV.USERS
(
    ID   NUMBER PRIMARY KEY,
    NAME VARCHAR2(255)
);

CREATE TABLE C##DEV.ISSUES
(
    ID      NUMBER,
    TITLE   VARCHAR2(255),
    USER_ID NUMBER REFERENCES C##DEV.USERS (ID)
);

CREATE TABLE C##DEV.TASKS
(
    ID NUMBER
);

-- Создание уникального индекса
CREATE UNIQUE INDEX C##DEV.ISSUES_UNIQ ON C##DEV.ISSUES (TITLE);

-- Создание функции
CREATE OR REPLACE FUNCTION C##DEV.TEST RETURN VARCHAR2 IS
BEGIN
    RETURN 'HELLO WORLD!';
END;
/

-- Создание триггера
CREATE OR REPLACE TRIGGER C##DEV.TEST_TRIGGER
    BEFORE DELETE OR INSERT OR UPDATE
    ON C##DEV.ISSUES
    FOR EACH ROW
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('TEST TRIGGER');
END;
/