-- Триггер для журналирования действий над таблицей STUDENTS
CREATE OR REPLACE TRIGGER students_audit_trigger
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
BEGIN
    -- Для операции INSERT
    IF INSERTING THEN
        INSERT INTO STUDENTS_AUDIT (OPERATION, STUDENT_ID, NEW_NAME, NEW_GROUP_ID)
        VALUES ('INSERT', :NEW.ID, :NEW.NAME, :NEW.GROUP_ID);
    END IF;

    -- Для операции UPDATE
    IF UPDATING THEN
        INSERT INTO STUDENTS_AUDIT (OPERATION, STUDENT_ID, OLD_NAME, NEW_NAME, OLD_GROUP_ID, NEW_GROUP_ID)
        VALUES ('UPDATE', :OLD.ID, :OLD.NAME, :NEW.NAME, :OLD.GROUP_ID, :NEW.GROUP_ID);
    END IF;

    -- Для операции DELETE
    IF DELETING THEN
        INSERT INTO STUDENTS_AUDIT (OPERATION, STUDENT_ID, OLD_NAME, OLD_GROUP_ID)
        VALUES ('DELETE', :OLD.ID, :OLD.NAME, :OLD.GROUP_ID);
    END IF;
END;
/



